import{a as L,S as b,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))t(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&t(d)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const w="51318694-35374bea804290f3a0783253d",S="https://pixabay.com/api/",v=15;async function h(e,r=1){try{return(await L.get(S,{params:{key:w,q:encodeURIComponent(e),image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:v}})).data}catch(s){throw console.error("API Error:",s),new Error("Failed to fetch images. Please try again later.")}}let u;function q(){u=new b(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function g(){u&&u.refresh()}function y(e){const r=document.querySelector(".gallery");if(!r)return;const s=e.map(t=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t.largeImageURL}">
        <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
        <div class="image-info">
          <p><b>Likes</b> ${t.likes}</p>
          <p><b>Views</b> ${t.views}</p>
          <p><b>Comments</b> ${t.comments}</p>
          <p><b>Downloads</b> ${t.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",s),g()}function E(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}let i=1,m="",a=0;const p=15;function P(){const e=document.querySelector(".form"),r=document.querySelector(".load-more-btn");return!e||!r?(console.error("Critical elements not found in DOM"),null):{form:e,loadMoreBtn:r}}document.addEventListener("DOMContentLoaded",()=>{const e=P();if(!e){l("Failed to initialize app - missing critical elements");return}q(),R(e)});function R({form:e,loadMoreBtn:r}){e.addEventListener("submit",async s=>{s.preventDefault();const t=s.target.elements.searchQuery.value.trim();t?await I(t):l("Please enter a search term!")}),r.addEventListener("click",async()=>{await M()})}async function I(e){const r=document.querySelector(".preloader"),s=document.querySelector(".notification"),t=document.querySelector(".load-more-btn");try{r.classList.remove("is-hidden"),s.classList.remove("is-hidden"),s.textContent="Loading images...",t.classList.add("is-hidden"),m=e,i=1,E();const o=await h(m,i);if(!o.hits||o.hits.length===0){O("No images found for your query!");return}a=o.totalHits,y(o.hits),$(`Hooray! We found ${a} images.`),a>p&&t.classList.remove("is-hidden")}catch(o){console.error("Search error:",o),l(o.message||"Failed to load images")}finally{r.classList.add("is-hidden"),s.classList.add("is-hidden")}}async function M(){const e=document.querySelector(".preloader"),r=document.querySelector(".notification"),s=document.querySelector(".load-more-btn");try{e.classList.remove("is-hidden"),r.classList.remove("is-hidden"),r.textContent="Loading more images...",i+=1;const t=await h(m,i);if(!t.hits||t.hits.length===0){f("No more images available"),s.classList.add("is-hidden");return}y(t.hits),g(),i*p>=a&&(s.classList.add("is-hidden"),f("We're sorry, but you've reached the end of search results.")),x()}catch(t){console.error("Load more error:",t),l(t.message||"Failed to load more images")}finally{e.classList.add("is-hidden"),r.classList.add("is-hidden")}}function x(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const{height:r}=e[0].getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}function l(e){c.error({title:"Error",message:e,position:"topRight"})}function O(e){c.warning({title:"Warning",message:e,position:"topRight"})}function f(e){c.info({title:"Info",message:e,position:"topRight"})}function $(e){c.success({title:"Success",message:e,position:"topRight"})}
//# sourceMappingURL=index.js.map
