import{a as L,i as w,S}from"./assets/vendor-DDdXnYQq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&t(u)}).observe(document,{childList:!0,subtree:!0});function a(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(r){if(r.ep)return;r.ep=!0;const n=a(r);fetch(r.href,n)}})();async function h(e,o=1){const a="https://pixabay.com/api/",t={key:"51318694-35374bea804290f3a0783253d",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await L.get(a,{params:t})).data}catch{throw new Error("Failed to fetch images from Pixabay API")}}let d;function m(){const e=document.querySelector(".preloader");e&&(e.style.display="flex")}function p(){const e=document.querySelector(".preloader");e&&(e.style.display="none")}function g(){const e=document.querySelector(".load-more-btn");e&&(e.style.display="block")}function l(){const e=document.querySelector(".load-more-btn");e&&(e.style.display="none")}function s(e,o="error"){w[o]({title:o==="error"?"Error":"Info",message:e,position:"topRight"})}function b(e,o){if(!e||e.length===0){s("Sorry, there are no images matching your search query. Please try again!");return}const a=e.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${t.likes}</p>
            <p><b>Views:</b> ${t.views}</p>
            <p><b>Comments:</b> ${t.comments}</p>
            <p><b>Downloads:</b> ${t.downloads}</p>
          </div>
        </a>
      `).join("");o.insertAdjacentHTML("beforeend",a),v()}function q(e){e.innerHTML=""}function v(){d?d.refresh():d=new S(".gallery a",{captionsData:"alt",captionDelay:250})}const P=document.querySelector(".form"),f=document.querySelector(".gallery"),B=document.querySelector(".load-more-btn");let i=1,y="",c=0;P.addEventListener("submit",async e=>{e.preventDefault();const a=new FormData(e.currentTarget).get("searchQuery").trim();if(!a){s("Please enter a search term!");return}y=a,i=1;try{m(),l(),q(f);const t=await h(y,i);if(c=t.totalHits,t.hits.length===0){s("Sorry, there are no images matching your search query. Please try again!");return}b(t.hits,f),s(`Hooray! We found ${c} images.`,"success"),t.hits.length<15||i*15>=c?l():g()}catch(t){s(t.message)}finally{p()}});B.addEventListener("click",async()=>{i+=1;try{m(),l();const e=await h(y,i);b(e.hits,f);const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),i*15>=c?(l(),s("We're sorry, but you've reached the end of search results.")):g()}catch(e){s(e.message)}finally{p()}});
//# sourceMappingURL=index.js.map
